version: "2"

volumes:
  ipython_history: {}

services:
  web_base:
    build: .
    networks:
      - backend
    external_links:
      - rabbit-day7:rabbit
#    command: ./run_rpc.sh

    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"
        RABBIT_MANAGEMENT_PORT: "15672"


  web:
    extends: web_base
    ports:
      - "8000:8000"
    networks:
      - front
#    command: ./run.sh

  rpc:
    extends: web_base
    ports:
      - "8001:8001"
    networks:
      - backend
    command: ./run_rpc.sh

   # command: sphinx-autobuild docs sphinx-docs -H 0.0.0.0 -p 8001


networks:
  backend:
    driver: bridge
  front: