version: "2"

volumes:
  ipython_history: {}

services:
  web_base:
    build: .

    ports:
      - "8000:8000"
    networks:
      - front
      - backend
    external_links:
      - rabbit-day7:rabbit
    command: ./run.sh

    environment:
      - RABBIT_PASSWORD=guest
      - RABBIT_USER=guest
      - RABBIT_HOST=rabbit
      - RABBIT_PORT=5672
      - RABBIT_MANAGEMENT_PORT=15672
      - SETTINGS_MODULE=service.config.settings.common

networks:
  backend:
    driver: bridge
  front: