version: "2"

volumes:
  ipython_history: {}

services:
  rabbit:
    container_name: rabbit-day7
    image: rabbitmq:3.6.5
    ports:
      - "5672:5672"
    networks:
      - backend
  web_base:
    build: .
    depends_on:
      - rabbit
    links:
      - "rabbit:rabbit-day7"
    ports:
      - "8000:8000"
    networks:
      - backend
    command: ./run.sh

    environment:
      - RABBIT_PASSWORD=guest
      - RABBIT_USER=guest
      - RABBIT_HOST=rabbit
      - RABBIT_PORT=5672
      - RABBIT_MANAGEMENT_PORT=15672
      - SETTINGS_MODULE=gateway

networks:
  backend:
    driver: bridge
